version: '2'
services:
  uitests:
    build:
      context: .
      dockerfile: Dockerfile
    image: uitests
    # depends_on:
      # - firefox
      # - web
    volumes:
      - .:/tests
      - /tests/node_modules
    environment:
      - CODECEPT_ARGS=--debug
      - ENVIRONMENT=dev
    stdin_open: true
    tty: true
  # firefox:
  #   image: selenium/standalone-firefox-debug:2.53.0
  #   ports:
  #     - '4444'
  #     - '5900'
